//
//	SpriteStudio6 Player for Unity
//
//	Copyright(C) 1997-2021 Web Technology Corp.
//	Copyright(C) CRI Middleware Co., Ltd.
//	All rights reserved.
//
struct InputVS
{
	float4 vertex : POSITION;
	float4 color : COLOR0;
	float4 texcoord : TEXCOORD0;	/* .x:U / .y:V / .z:PartsColor-Blend / .w:PartsColor-Power */
	float4 texcoord1 : TEXCOORD1;	/* .x:U-Min / .y:V-Min / .z:U-Max / .w:V-Max */
	float4 texcoord2 : TEXCOORD2;	/* .x:U-Avr / .y:V-Avr / (No-Use) / .w:(No-Use) */
};

struct InputPS
{
	float4 Position : PIXELSHADER_BINDDATA_POSITION;
	float4 ColorMain : COLOR0;
	float4 ColorOverlay : COLOR1;
#if defined(RESTRICT_SHADER_MODEL_3)
	float4 ParameterOverlay : TEXCOORD0;
// #else
#endif
	float4 ArgumentVs00 : TEXCOORD1;
	float4 Texture00UV : TEXCOORD2;
	float4 Texture00UVMinMax : TEXCOORD3;
	float4 Texture00UVAverage : TEXCOORD4;
	float4 PositionDraw : TEXCOORD15;
};

/* Common(Vertex and Pixel) Uniform */
/* MEMO: In "SpriteStudio 6.x" implementation, shader-parameters are as follows.                             */
/*       However, in "SS6Player for Unity" implementation, only datas related to texture(CellMap) are set to */
/*        Uniform. UV-datas(Cell) are included in vertex-data.                                               */
/*       (This implementation is considering "Efficiency of Mesh-Batching" in case of that "Minimum-U/V",    */
/*        "Maximum-U/V" and "Average-U/V" are used in SS6PU's standard-shaders in the future.)               */
/*                                                                                                           */
/*       [Caution] Uniforms with "x" bullet points do not currently exist in "SS6Player for Unity".          */
/*                                                                                                           */
/*       - ArgumentVs00 : Set of parameters for Vertex-Shader generated by SpriteStudio6.x                   */
/*           .x : Effective rate of (Albedo-)Texture                                                         */
/*           .y : Effective rate of Vertex-Color                                                             */
/*           .z : Effective rate of (Albedo-)Texture to Vertex-Color                                         */
/*           .w : (No Use)                                                                                   */
/*                                                                                                           */
/*       - ArgumentFs00 : Set of parameters for Pixel-Shader generated by SpriteStudio6.x (Part 0)           */
/*           .x : Texture's pixel size X [A_TW]                                                              */
/*           .y : Texture's pixel size Y [A_TH]                                                              */
/*           .z : U-value per pixel [A_U1]                                                                   */
/*           .w : V-value per pixel [A_V1]                                                                   */
/*       x ArgumentFs01 : Set of parameters for Pixel-Shader generated by SpriteStudio6.x (Part 1)           */
/*         *) These values are relocated to "texcoord1.x", "texcoord1.y", "texcoord2.x", and "texcoord2.y"   */
/*              in Vertex-Data (and Pixel-Shader's input "Texture00UVMinMax.x", "Texture00UVMinMax.y"        */
/*              "Texture00UVMinMax.z". "Texture00UVMinMax.w").                                               */
/*           .x : Minimum-U of cell [A_LU]                                                                   */
/*           .y : Minimum-V of cell [A_TV]                                                                   */
/*           .z : Average-U of cell [A_CU]                                                                   */
/*           .w : Average-V of cell [A_CV]                                                                   */
/*       x ArgumentFs02 : Set of parameters for Pixel-Shader generated by SpriteStudio6.x (Part 2)           */
/*         *) These values are relocated to "texcoord1.z" and "texcoord1.w" in Vertex-Data                   */
/*              (and Pixel-Shader's input "Texture00UVAverage.x", "Texture00UVAverage.y").                   */
/*         *) ".z" is relocated to "PS_OUTPUT_PMA" (Vertex/Pixel Shader's compile-option).                   */
/*           .x : Maximum-U of cell [A_RU]                                                                   */
/*           .y : Maximum-V of cell [A_BV]                                                                   */
/*           .z : PMA processing of pixel's RGB (0.0f: No-effect / 1.0f: Effect) [A_PM]                      */
/*           .w : Reserved (Now not use)                                                                     */
/*       x ArgumentFs03 : Set of parameters for Pixel-Shader generated by SpriteStudio6.x (Part 3)           */
/*           .x : Reserved (Now not use)                                                                     */
/*           .y : Reserved (Now not use)                                                                     */
/*           .z : Reserved (Now not use)                                                                     */
/*           .w : Reserved (Now not use)                                                                     */
/*                                                                                                           */
/*       - ParameterFs00 : Values of "Shader"-attribute set in "SpriteStudio 6.x"                            */
/*           .x : Shader Data 0 (param0)                                                                     */
/*           .y : Shader Data 1 (param1)                                                                     */
/*           .z : Shader Data 2 (param2)                                                                     */
/*           .w : Shader Data 3 (param3)                                                                     */
/*       x ParameterFs01 : (Reserved)                                                                        */
/*           .x : Reserved (Now not use)                                                                     */
/*           .y : Reserved (Now not use)                                                                     */
/*           .z : Reserved (Now not use)                                                                     */
/*           .w : Reserved (Now not use)                                                                     */
/*       x ParameterFs02 : (Reserved)                                                                        */
/*           .x : Reserved (Now not use)                                                                     */
/*           .y : Reserved (Now not use)                                                                     */
/*           .z : Reserved (Now not use)                                                                     */
/*           .w : Reserved (Now not use)                                                                     */
/*       x ParameterFs03 : (Reserved)                                                                        */
/*           .x : Reserved (Now not use)                                                                     */
/*           .y : Reserved (Now not use)                                                                     */
/*           .z : Reserved (Now not use)                                                                     */
/*           .w : Reserved (Now not use)                                                                     */
// float4 FlagsControl;
// float4 _ArgumentVs00;
float4 _ArgumentFs00;	/* A_TW, A_TH, A_U1, A_V1 */
// float4 _ArgumentFs01;	/* A_LU, A_TV, A_CU, A_CV */
// float4 _ArgumentFs02;	/* A_RU, A_BV, A_PM, (Reserved) */
// float4 _ArgumentFs03;
float4 _ParameterFs00;	/* param0, param1, param2, param3 (Attribute "Shader") */
// float4 _ParameterFs01;
// float4 _ParameterFs02;
// float4 _ParameterFs03;

// #define VertexSettingRateTexture	ArgumentVs00.x
// #define VertexSettingRateVertex	ArgumentVs00.y
// #define VertexSettingRateTextureToVertex	ArgumentVs00.z

#define PixelSettingTextureSizeX	_ArgumentFs00.x
#define PixelSettingTextureSizeY	_ArgumentFs00.y
#define PixelSettingPerTexelU	_ArgumentFs00.z
#define PixelSettingPerTexelV	_ArgumentFs00.w
// #define PixelSettingMinimumU	ArgumentFs01.x
// #define PixelSettingMinimumV	ArgumentFs01.y
// #define PixelSettingAverageU	ArgumentFs01.z
// #define PixelSettingAverageV	ArgumentFs01.w
// #define PixelSettingMaximumU	ArgumentFs02.x
// #define PixelSettingMaximumV	ArgumentFs02.y
// #define PixelSettingTexelPMA	ArgumentFs02.z

#define ShaderParameter0	_ParameterFs00.x
#define ShaderParameter1	_ParameterFs00.y
#define ShaderParameter2	_ParameterFs00.z
#define ShaderParameter3	_ParameterFs00.w
